import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
const base=(process.env.BASE_PATH || '').replace(/\/$/,'');
if(base && !/^\/[a-zA-Z0-9_-]+(?:\/[a-zA-Z0-9_-]+)*$/.test(base)) throw new Error('Invalid BASE_PATH');
const data=JSON.parse(await readFile('src/content.json','utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=['公共工事','工場・倉庫','店舗','事務所','改修工事','外構','その他'];
const nav=[['/construction/','建築事業'],['/business/','法人向け工事'],['/public/','公共工事'],['/real-estate/','不動産事業'],['/projects/','施工実績'],['/company/','会社概要'],['/recruit/','採用情報']];
const arrow='<span aria-hidden="true">↗</span>';
const button=(href,label,secondary=false)=>`<a class="button ${secondary?'secondary':''}" href="${href}">${label}${arrow}</a>`;
function art(kind='building',label='施工写真準備中'){return `<div class="architecture ${kind}" role="img" aria-label="建築物を描いたプレースホルダー。${esc(label)}"><div class="drawing"><i></i><i></i><i></i><i></i><i></i></div><span class="art-label">DREAM QUEST BUILD / ${esc(label)}</span></div>`;}
function photo(p){return p.photos?.length?`<img class="project-image" src="${esc(p.photos[0].src)}" alt="${esc(p.photos[0].alt)}" loading="lazy">`:art(p.category==='工場・倉庫'?'warehouse':p.category==='店舗'?'store':'building');}
function projectCard(p){return `<a class="project-card" href="/projects/${esc(p.slug)}/">${photo(p)}<div class="project-info"><small>${esc(p.category)}${p.sample?' / 掲載イメージ':''}</small><h3>${esc(p.name)} ${arrow}</h3><p>${p.sample?'実績情報・写真は確認後に掲載します。':esc(p.location)}</p></div></a>`;}
const reasons=[['01','↗','見積回答が速い','ご相談内容を速やかに確認し、見積の段取りを進めます。'],['02','◎','現地調査への対応が速い','現場の状況を把握し、次の一手を早く。'],['03','▤','施工管理まで任せられる','工程・品質・安全を見据え、現場を管理。'],['04','＋','小工事でも対応','小さな修繕や部分工事からご相談ください。'],['05','☾','夜間工事対応','営業や稼働への影響を考え、施工時間を調整。'],['06','◇','大阪府全域対応','堺市を拠点に、大阪府全域へ。'],['07','→','他府県への出張対応可能','エリア外の案件も、条件に応じて対応。'],['08','▦','一式請負可能','工事全体を見渡し、まとめて相談できる体制。']];
const reasonCards=()=>`<div class="reason-grid">${reasons.map(([n,i,t,d])=>`<article class="reason"><div class="reason-top"><span>${n}</span><b aria-hidden="true">${i}</b></div><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>`;
const heading=(en,ja,desc='')=>`<div class="section-heading"><span class="eyebrow">${en}</span><h2>${ja}</h2>${desc?`<p>${desc}</p>`:''}</div>`;
const cta=()=>`<section class="contact-band"><div><span class="eyebrow">LET’S BUILD TOGETHER</span><h2>その現場の課題、<br>まずはご相談ください。</h2><p>急ぎの工事も、小さな修繕も。<br>見積・現地調査のご相談から承ります。</p></div><div class="cta-buttons">${button('/contact/','お問い合わせ')}${button('/contact/?type=現地調査依頼','見積・現調のご相談',true)}<small>大阪府全域対応 / 他府県への出張もご相談ください</small></div></section>`;
const rows=items=>`<dl class="details">${items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;
const pageHero=(en,title,desc)=>`<div class="page-hero"><div class="container"><p class="breadcrumbs"><a href="/">TOP</a> <span>/</span> ${title}</p><span class="eyebrow">${en}</span><h1>${title}</h1><p>${desc}</p></div></div>`;
const pages=[];
function add(route,title,description,body){pages.push({route,title,description,body});}
add('/','堺市・大阪の建設会社','大阪府堺市の株式会社ドリームクエスト。建築・改修・修繕から施工管理まで。法人向け工事、公共工事、工場・倉庫、店舗工事をご相談ください。',`
<section class="hero"><div class="hero-content"><p class="eyebrow">OSAKA / SAKAI — CONSTRUCTION PARTNER</p><h1>現場を止めない。<br>仕事で応える。</h1><p class="hero-description">建築・改修・修繕から施工管理まで。<br>大阪府全域、迅速に対応。</p><div class="hero-actions">${button('/contact/','お問い合わせ')}${button('/contact/?type=見積依頼','見積・現調のご相談',true)}</div><p class="hero-note">大阪で一番頼られる下請け建設会社を目指す。</p></div>${art('hero-art','PHOTO PLACEHOLDER')}<div class="hero-bottom"><span>確かな管理。柔軟な対応。現場に、前進を。</span><a href="#strengths">SCROLL ↓</a></div></section>
<div class="quick-strip"><span>元請・下請対応</span><span>施工管理・一式請負</span><span>小工事・夜間工事</span><span>大阪府全域・他府県出張</span></div>
<section class="section container" id="strengths"><div class="intro"><div>${heading('OUR STRENGTHS','頼れる体制と、<br>動ける機動力。')}</div><p>現場ごとに異なる条件に向き合い、工事を前へ進める。<br>企業としての施工管理と、中小建設会社ならではの柔軟さで、<br>発注者様・元請企業様の仕事を支えます。</p></div>${reasonCards()}</section>
<section class="section service-section"><div class="container">${heading('OUR BUSINESS','建築を軸に、事業を支える。','新築から日々の修繕、公共施設、不動産まで。一つの窓口でご相談いただけます。')}<div class="service-grid">${[['01','建築事業','新築・改修・設計施工。現場と向き合う総合的な建築対応。','/construction/'],['02','法人向け工事','店舗・工場・倉庫・事務所。事業を止めない工事のご相談。','/business/'],['03','公共工事','建築・土木・修繕。公共施設の改修にも対応。','/public/'],['04','不動産事業','建築と不動産を一体で。土地・建物の可能性を考えます。','/real-estate/']].map(([n,t,d,h])=>`<a class="service-card" href="${h}"><span class="service-number">${n}</span><h3>${t}${arrow}</h3><p>${d}</p></a>`).join('')}</div></div></section>
<section class="section container"><div class="heading-row">${heading('SELECTED WORKS','仕事が、信頼になる。','施工実績は情報確認後に掲載予定です。以下は掲載イメージです。')}<a class="text-link" href="/projects/">施工実績一覧 ${arrow}</a></div><div class="project-grid">${data.projects.slice(0,3).map(projectCard).join('')}</div></section>
<section class="company-teaser container"><div>${art('warehouse','COMPANY / PHOTO PLACEHOLDER')}</div><div><span class="eyebrow">ABOUT US</span><h2>堺から、大阪の<br>建設を支える。</h2><p>株式会社ドリームクエストは、建築・施工管理を軸に、法人・公共・不動産のご相談に応えます。個々の現場に必要な対応を、会社として届けます。</p><a class="text-link" href="/company/">会社概要 ${arrow}</a></div></section>
<section class="section container news-section">${heading('INFORMATION','お知らせ')}<div class="news-list">${data.news.map(n=>`<article><span>${esc(n.date||'準備中')}</span><div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div></article>`).join('')}</div></section>
<a class="recruit-banner container" href="/recruit/"><div><span class="eyebrow">CAREERS</span><h2>次の現場を、共につくる。</h2><p>施工管理経験を、会社の成長を支える力へ。</p></div><span class="text-link">採用情報 ${arrow}</span></a>${cta()}`);
const services=[
['/construction/','CONSTRUCTION','建築事業','新築から改修・修繕まで。現場に合わせた建築対応。','元請としても、下請としても。','工事の規模や発注形態に合わせ、施工から管理まで柔軟に対応します。工程・品質・安全を見据え、現場全体を支えるパートナーを目指します。',['新築','改修','リフォーム','店舗','事務所','工場','倉庫','住宅','解体','外構','その他建築工事'],['公共施設大規模改修','工場・倉庫','店舗','設計施工']],
['/business/','FOR BUSINESS','法人向け工事','事業の現場に必要な工事を、一つの相談窓口へ。','どこへ頼めばよいか分からない工事も。','店舗の出店から原状回復、建物の日常的な営繕まで。用途・稼働状況・希望時期を伺い、現地調査から工事の進め方をご相談いただけます。',['店舗出店支援','工場・倉庫','事務所','原状回復','営繕','修繕','その他法人案件'],['営業・稼働への配慮','夜間工事のご相談','小規模修繕','一式請負']],
['/public/','PUBLIC WORKS','公共工事','公共施設の建築・改修・修繕を、確かな管理で。','施設の役割を、次の時代へ。','公共施設の大規模改修をはじめ、建築・土木・修繕などのご相談に対応します。施設利用や周辺環境を踏まえた施工計画を大切にします。',['建築','土木','修繕','その他公共工事'],['公共施設大規模改修','工程管理','品質管理','安全管理']],
['/real-estate/','REAL ESTATE','不動産事業','建築と不動産を、一体で相談できる会社へ。','土地と建物の、その先まで。','建設会社としての知識を活かし、物件の活用や建築・改修の可能性を含めて考えます。事業用不動産や土地活用など、幅広いご相談を承ります。',['売買仲介','不動産買取','事業用不動産','土地活用','収益不動産','開発','その他不動産相談'],['建築と不動産の一体相談','用途に合わせた活用検討','改修・修繕の相談','事業用物件の相談']]
];
for(const [route,en,title,desc,lead,text,tags,features] of services){add(route,title,`${desc}株式会社ドリームクエストが大阪府堺市を拠点に対応します。`,`${pageHero(en,title,desc)}<section class="section container split"><div>${art(route==='/business/'?'warehouse':'building')}</div><div><span class="eyebrow">OUR APPROACH</span><h2>${lead}</h2><p>${text}</p>${button('/contact/?type='+encodeURIComponent(route==='/real-estate/'?'不動産相談':route==='/public/'?'公共工事関連':'建設工事相談'),'この事業について相談する')}</div></section><section class="section container">${heading('SCOPE OF WORK','対応内容')}<div class="tag-grid">${tags.map(t=>`<div>${t}<span>↗</span></div>`).join('')}</div></section><section class="section muted"><div class="container">${heading('FOCUS','私たちが大切にすること')}<div class="feature-grid">${features.map((t,i)=>`<article><span class="eyebrow">0${i+1}</span><h3>${t}</h3></article>`).join('')}</div>${route==='/public/'?`<div class="qualification"><h3>入札参加資格</h3>${rows([['堺市 入札参加資格',data.company.sakaiQualification],['大阪府 入札参加資格',data.company.osakaQualification]])}<p>資格の登録状況・対象区分は確認後に掲載します。</p></div>`:''}${route==='/real-estate/'?rows([['宅地建物取引業免許',data.company.realEstateLicense]]):''}</div></section><section class="section container">${heading('CONSULTATION FLOW','ご相談から施工まで')}<ol class="flow"><li><b>01 / ご相談</b><p>工事内容・場所・希望時期をお知らせください。</p></li><li><b>02 / 現地調査・見積</b><p>現場の条件を確認し、工事の進め方をご相談します。</p></li><li><b>03 / 計画・施工</b><p>合意した内容に沿って、施工・管理を進めます。</p></li><li><b>04 / 完了・ご確認</b><p>施工内容をご確認いただき、引き渡します。</p></li></ol></section>${cta()}`);}
add('/projects/','施工実績','公共工事、工場・倉庫、店舗、事務所、改修工事、外構などの施工実績をご紹介するページです。',`${pageHero('OUR WORKS','施工実績','一つひとつの現場への対応を、仕事で示す。')}<section class="section container"><p class="notice">現在は掲載イメージです。実際の工事名・所在地・施工内容・写真は、確認後に掲載します。</p><div class="filters" role="group" aria-label="施工実績カテゴリー"><button class="active" aria-pressed="true" data-filter="all">すべて</button>${categories.map(c=>`<button aria-pressed="false" data-filter="${c}">${c}</button>`).join('')}</div><p class="filter-status" role="status">全 ${data.projects.length} 件</p><div class="project-grid" id="project-list">${data.projects.map(p=>`<div data-category="${p.category}">${projectCard(p)}</div>`).join('')}</div></section>${cta()}`);
for(const p of data.projects){add(`/projects/${p.slug}/`,p.name,`${p.name}の掲載ページ。株式会社ドリームクエストの施工実績。`,`${pageHero('PROJECT DETAIL',esc(p.name),esc(p.category))}<section class="section container narrow">${p.sample?'<p class="notice">掲載イメージです。実際の施工実績を示すものではありません。情報・写真は確認後に掲載します。</p>':''}${photo(p)}${rows([['工事名',p.sample?'PLACEHOLDER：確認後入力':p.name],['工事種別',p.category],['所在地',p.location],['施工内容',p.scope],['竣工時期',p.completed]])}<h2>施工写真</h2><div class="gallery">${p.photos.length?p.photos.map(f=>`<figure><img src="${esc(f.src)}" alt="${esc(f.alt)}" loading="lazy">${f.caption?`<figcaption>${esc(f.caption)}</figcaption>`:''}</figure>`).join(''):art('building','完成写真・施工中写真 / PLACEHOLDER')}</div><a class="text-link" href="/projects/">← 施工実績一覧へ</a></section>${cta()}`);}
add('/company/','会社概要','大阪府堺市の株式会社ドリームクエストの会社概要。建設業許可、宅地建物取引業免許、入札参加資格の掲載項目。',`${pageHero('COMPANY','会社概要','会社としての対応力で、現場の信頼に応える。')}<section class="section container narrow"><span class="eyebrow">OUR PHILOSOPHY</span><h2>大阪で一番頼られる<br>下請け建設会社を目指す。</h2><p class="large-copy">速く動くこと。柔軟に考えること。管理をおろそかにしないこと。<br>目の前の工事に誠実に向き合い、次の相談につながる仕事を積み重ねていきます。</p>${rows([['会社名',data.company.name],['所在地',data.company.address],['代表者',data.company.representative],['電話番号',data.company.phone],['事業内容','建築・法人向け工事・公共工事・不動産'],['建設業許可',data.company.constructionLicense],['宅地建物取引業免許',data.company.realEstateLicense],['堺市 入札参加資格',data.company.sakaiQualification],['大阪府 入札参加資格',data.company.osakaQualification]])}</section>${cta()}`);
add('/recruit/','採用情報','建築施工管理経験者、現場監督経験者、施工管理資格保有者、建設業界経験者へ。株式会社ドリームクエストの現場管理人材募集。',`${pageHero('CAREERS','採用情報','その経験が、会社の次の力になる。')}<section class="section container split"><div><span class="eyebrow">BUILD OUR FUTURE</span><h2>現場を動かす。<br>会社の未来をつくる。</h2><p>建築施工管理・現場管理の経験を活かし、会社の成長とともに中核メンバーを目指しませんか。施工の現場と会社の両方を支える仲間を募集します。</p>${button('/contact/?type=採用','応募・採用のご相談')}</div>${art('building','RECRUIT / PHOTO PLACEHOLDER')}</section><section class="section container narrow">${heading('REQUIREMENTS','募集要項')}<p>建築施工管理経験者・現場監督経験者・施工管理資格保有者・建設業界経験者を対象に募集しています。具体的な応募条件は確認後に掲載します。</p>${rows([['募集職種',data.recruit.role],['雇用形態',data.recruit.employment],['給与',data.recruit.salary],['勤務時間',data.recruit.hours],['休日',data.recruit.holidays],['福利厚生',data.recruit.benefits],['勤務地',data.recruit.location]])}${button('/contact/?type=採用','応募フォームへ')}</section>`);
const inquiryTypes=['見積依頼','現地調査依頼','建設工事相談','協力会社／下請依頼','不動産相談','公共工事関連','採用','その他'];
const field=(name,label,type='text',required=false,extra='')=>`<label class="form-field"><span>${label} ${required?'<b>必須</b>':'<small>任意</small>'}</span><input type="${type}" name="${name}" ${required?'required':''} ${extra}></label>`;
add('/contact/','お問い合わせ','見積依頼・現地調査・建設工事・協力会社・不動産・公共工事・採用のご相談。急ぎの工事、小規模修繕もお気軽に。',`${pageHero('CONTACT','お問い合わせ','急ぎの工事も、小さな修繕も。まずはご相談ください。')}<section class="section container narrow"><div class="notice"><strong>プレビュー版：このフォームは送信されません。</strong><p>入力内容の確認までお試しいただけます。送信先・個人情報の取扱方針は正式公開前に設定します。テストには架空の情報をご使用ください。</p></div><form id="contact-form"><div class="form-grid">${field('company','会社名','text',false,'autocomplete="organization" maxlength="120"')}${field('name','担当者名','text',true,'autocomplete="name" maxlength="100"')}${field('phone','電話番号','tel',false,'autocomplete="tel" maxlength="40"')}${field('email','メールアドレス','email',true,'autocomplete="email" maxlength="254"')}</div><label class="form-field"><span>問い合わせ種別 <b>必須</b></span><select name="type" required><option value="">選択してください</option>${inquiryTypes.map(t=>`<option>${t}</option>`).join('')}</select></label><div class="form-grid">${field('location','工事場所','text',false,'maxlength="200"')}${field('timing','希望時期','text',false,'placeholder="例：できるだけ早く、来月以降" maxlength="100"')}</div><label class="form-field"><span>問い合わせ内容 <b>必須</b></span><textarea name="message" rows="7" required maxlength="5000" placeholder="工事の内容や規模、現在のお困りごとをお知らせください。"></textarea></label><label class="checkbox"><input type="checkbox" required> プレビュー版であり、実際には送信されないことを確認しました。</label><button class="button" type="submit">入力内容を確認する ${arrow}</button></form><section id="confirmation" hidden tabindex="-1"><h2>入力内容の確認</h2><p class="notice">確認のみ完了しました。お問い合わせは送信されていません。入力内容はサーバーに保存されません。</p><dl class="details" id="confirmation-data"></dl><button class="button secondary" id="edit-form" type="button">入力内容を修正する</button></section></section>`);
add('/privacy/','個人情報の取扱い','お問い合わせに関する個人情報の取扱いについて。',`${pageHero('PRIVACY','個人情報の取扱い','正式な方針は確認後に掲載します。')}<section class="section container narrow"><p class="notice">PLACEHOLDER：確認後入力</p><p>お問い合わせの利用目的、保管期間、第三者提供、管理体制、お問い合わせ窓口等の正式な方針を、会社で確認のうえ掲載してください。</p><p>現在のプレビュー版フォームは、入力内容を送信・保存しません。</p></section>`);
await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
for(const p of pages){const canonical='https://dreamquest-build.com'+p.route;const html=`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)} | DREAM QUEST BUILD</title><meta name="description" content="${esc(p.description)}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="${canonical}"><meta property="og:locale" content="ja_JP"><meta property="og:type" content="website"><meta property="og:site_name" content="DREAM QUEST BUILD"><meta property="og:title" content="${esc(p.title)} | DREAM QUEST BUILD"><meta property="og:description" content="${esc(p.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://dreamquest-build.com/images/ogp.svg"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#102736"><link rel="icon" href="/images/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body><a class="skip-link" href="#main">本文へ移動</a><header class="site-header"><a class="brand" href="/" aria-label="DREAM QUEST BUILD トップ"><span class="brand-mark" aria-hidden="true">DQ<span>／</span></span><span><strong>DREAM QUEST <b>BUILD</b></strong><small>株式会社ドリームクエスト</small></span></a><button class="menu-toggle" aria-label="メニューを開く" aria-expanded="false" aria-controls="main-nav">MENU <span>☰</span></button><nav id="main-nav" aria-label="メインナビゲーション">${nav.map(([url,t])=>`<a href="${url}" ${p.route.startsWith(url)?'aria-current="page"':''}>${t}</a>`).join('')}<a class="nav-contact" href="/contact/" ${p.route==='/contact/'?'aria-current="page"':''}>お問い合わせ ↗</a></nav></header><main id="main">${p.body}</main><footer><div class="container footer-top"><div><a class="footer-brand" href="/">DREAM QUEST <b>BUILD</b></a><p>株式会社ドリームクエスト<br>大阪府堺市</p><p class="footer-tagline">現場を止めない。仕事で応える。</p></div><nav aria-label="フッターナビゲーション">${nav.map(([u,t])=>`<a href="${u}">${t}</a>`).join('')}<a href="/contact/">お問い合わせ</a></nav></div><div class="container footer-bottom"><a href="/privacy/">個人情報の取扱い</a><span>© DREAM QUEST Co., Ltd.</span><span>PREVIEW / 公開準備中</span></div></footer></body></html>`;await mkdir('dist'+p.route,{recursive:true});await writeFile('dist'+p.route+'index.html',html.replace(/(href|src)="\/(?!\/)/g, '$1="'+base+'/'));}
await writeFile('dist/robots.txt','User-agent: *\nDisallow: /\n');
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.map(p=>`<url><loc>https://dreamquest-build.com${p.route}</loc></url>`).join('')+'</urlset>');
console.log(`Built ${pages.length} pages (preview: noindex, contact confirmation only).`);
